spring:
  datasource:
    url: jdbc:h2:mem:api
    username: sa
    password:
  jpa:
    show-sql: true
    open-in-file: false
    hibernate:
      ddl-auto: create #validate | update | create | create-drop
    properties:
      hibernate:
        format-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false